# Generated by Django 3.2.9 on 2021-11-15 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0003_ingredient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_buy',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_buy', to=settings.AUTH_USER_MODEL),
        ),
    ]
